set(_CATKIN_CURRENT_PACKAGE "unity_flexiv_ros")
set(unity_flexiv_ros_VERSION "0.0.0")
set(unity_flexiv_ros_MAINTAINER "jonathan <jonathan@todo.todo>")
set(unity_flexiv_ros_PACKAGE_FORMAT "2")
set(unity_flexiv_ros_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(unity_flexiv_ros_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(unity_flexiv_ros_BUILDTOOL_DEPENDS "catkin")
set(unity_flexiv_ros_BUILDTOOL_EXPORT_DEPENDS )
set(unity_flexiv_ros_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(unity_flexiv_ros_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(unity_flexiv_ros_TEST_DEPENDS )
set(unity_flexiv_ros_DOC_DEPENDS )
set(unity_flexiv_ros_URL_WEBSITE "")
set(unity_flexiv_ros_URL_BUGTRACKER "")
set(unity_flexiv_ros_URL_REPOSITORY "")
set(unity_flexiv_ros_DEPRECATED "")